version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  auth-api:
    depends_on:
      - mariadb
      - mongo
    extends:
      file: ./compose/compose.published.yml
      service: auth-api

  user-api:
    depends_on:
      - mariadb
      - mongo
    extends:
      file: ./compose/compose.published.yml
      service: user-api

#  product-api:
#    extends:
#      file: ./compose/compose.published.yml
#      service: product-api

#  front:
#    extends:
#      file: ./compose/compose.published.yml
#      service: front

networks:
  default:
    external: true
    name: grpc-task-manager_default

