version: '3.8'

services:
  user-api:
    image: mohammaddocker/tm-user-api
    environment:
      - MYSQL_URL=mysql://root:passwd@mariadb:3306/user
      - insecure=true
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=4000
      - AUTH_API_URL=auth-api:4000
      - JAEGER_URL=http://tracing:4318/v1/traces
    ports:
      - "4000:4000"
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  auth-api:
    image: mohammaddocker/tm-auth-api
    environment:
      - MYSQL_URL=mysql://root:passwd@mariadb:3306/auth
      - insecure=true
      - AUTH_CERT=/certs/auth.pem
      - AUTH_KEY=/certs/auth-key.pem
      - PORT=4000
      - USER_API_URL=user-api:4000
      - JWT_SECRET=super-secret
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:4318/v1/traces
    ports:
      - "4002:4000"
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  product-api:
    build:
      context: ../product-api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:passwd@mariadb:3306/product
      - insecure=true
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=4000
    ports:
      - "4003:4000"
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  payment-api:
    build:
      context: ../payment-api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:passwd@mariadb:3306/payment
      - insecure=true
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=4000
    ports:
      - "4004:4000"
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  default:
    external: true
    name: grpc-task-manager_default